import { LoginContainer } from "./auth/LoginContainer";
import { GameStartPanel } from "./game/GameStartPanel";
import { MainNavbar } from "./navigation/MainNavbar";
import { LinkButton } from "./utils/LinkButton";
import { ChatView } from "./views/ChatView";
import { FriendsView } from "./views/FriendsView";
import { HomeView } from "./views/HomeView";
import { LoginView } from "./views/LoginView";
import { MainView } from "./views/MainView";
import { MyPageView } from "./views/MyPageView";
import { NotFoundView } from "./views/NotFoundView";
import { TournamentsView } from "./views/TournamentsView";
import { UsersView } from "./views/UsersView";

customElements.define("login-container", LoginContainer, {});
customElements.define("game-start-panel", GameStartPanel, {});
customElements.define("main-navbar", MainNavbar, {});
customElements.define("link-button", LinkButton, {});
customElements.define("chat-view", ChatView, {});
customElements.define("friends-view", FriendsView, {});
customElements.define("home-view", HomeView, {});
customElements.define("login-view", LoginView, {});
customElements.define("main-view", MainView, {});
customElements.define("my-page-view", MyPageView, {});
customElements.define("not-found-view", NotFoundView, {});
customElements.define("tournaments-view", TournamentsView, {});
customElements.define("users-view", UsersView, {});
