services:
  backend:
    container_name: backend
    restart: always
    ports:
      - "8000:8000"
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend:42
    env_file: .env
    # WORKDIR(Dockerfile): /pong
    volumes:
      - ./backend/pong:/pong
    networks:
      - transcendence

  db:
    image: postgres:17.0-bullseye
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - transcendence

networks:
  transcendence:
    name: trc-network
    driver: bridge

volumes:
  db-data:
    name: trc-db-data
