services:
  frontend:
    container_name: frontend
    image: frontend:42
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        SERVER_PORT: ${FRONT_SERVER_PORT}
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - ./backend/pong/media:/usr/share/nginx/html/media
    restart: always
    ports:
      - "${FRONT_SERVER_PORT}:443"
    networks:
      - transcendence
    healthcheck:
      test: ["CMD-SHELL", "curl -f https://localhost:443 -k || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 6

  backend:
    container_name: backend
    restart: always
    ports:
      - "${BACKEND_SERVER_PORT}:8000"
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend:42
    env_file: .env
    # WORKDIR(Dockerfile): /pong
    volumes:
      - ./backend/pong:/pong
    networks:
      - transcendence
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/api/health/ || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 6

  db:
    image: postgres:17.0-bullseye
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - transcendence
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME} -h localhost -p 5432 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 6

  adminer:
    container_name: adminer
    build:
      context: ./adminer
      dockerfile: Dockerfile
    image: adminer:42
    restart: always
    ports:
      - ${ADMINER_PORT}:8080
    depends_on:
      db:
        condition: service_healthy
    networks:
      - transcendence
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 6

  redis:
    image: redis:7.4.2-alpine
    container_name: redis
    restart: always
    command: [ "sh", "-c", "redis-server /usr/local/etc/redis/redis.conf --requirepass ${REDIS_PASSWORD}" ]
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - transcendence
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 6

networks:
  transcendence:
    name: trc-network
    driver: bridge

volumes:
  db-data:
    name: trc-db-data
