services:
  backend:
    container_name: backend
    restart: always
    ports:
      - "8000:8000"
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend:42
    env_file: .env
    # WORKDIR(Dockerfile): /pong
    volumes:
      - ./backend/pong:/pong
    networks:
      - transcendence
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/api/health/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

  # todo: DBが必要になってから追加
  # db:
  #   networks:
  #     - transcendence

networks:
  transcendence:
    name: trc-network
    driver: bridge
