services:
  frontend:
    container_name: frontend
    image: frontend:42
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      backend:
        condition: service_healthy
    restart: always
    ports:
      - "${FRONT_SERVER_PORT}:8080"
    networks:
      - transcendence
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${FRONT_SERVER_PORT} || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 6

  backend:
    container_name: backend
    restart: always
    ports:
      - "${BACKEND_SERVER_PORT}:8000"
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend:42
    env_file: .env
    # WORKDIR(Dockerfile): /pong
    volumes:
      - ./backend/pong:/pong
    networks:
      - transcendence
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${BACKEND_SERVER_PORT}/api/health/ || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 6

  db:
    image: postgres:17.0-bullseye
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - transcendence
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME} -h localhost -p 5432 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 6

  adminer:
    container_name: adminer
    build:
      context: ./adminer
      dockerfile: Dockerfile
    image: adminer:42
    restart: always
    ports:
      - ${ADMINER_PORT}:8080
    depends_on:
      db:
        condition: service_healthy
    networks:
      - transcendence
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${ADMINER_PORT} || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 6

networks:
  transcendence:
    name: trc-network
    driver: bridge

volumes:
  db-data:
    name: trc-db-data
