openapi: 3.0.0

# todo: APIのタイトル
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9

# todo: serverのurlと詳細
servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing

# todo: postなどの他のメソッドの定義（他のメソッドも定義する場合、/components/schemasを使用してresponseのcontentをまとめる）
paths:
  /health:
    get:
      summary: Health check endpoint
      description: This endpoint checks the health of the service instance by performing various checks, such as infrastructure connections, host status, and application-specific logic.
      responses:
        "200":
          description: The service is healthy and capable of handling requests.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "healthy"
                  message:
                    type: string
                    example: "The service is healthy and capable of handling requests."
                  timestamp:
                    type: string
                    format: date-time
                    example: "2024-11-09T12:00:00Z"
        "503":
          description: The service is unhealthy and unable to handle requests.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "unhealthy"
                  message:
                    type: string
                    example: "The service is unhealthy and unable to handle requests."
                  timestamp:
                    type: string
                    format: date-time
                    example: "2024-11-09T12:01:00Z"
        "500":
          description: Internal server error occurred during health check.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "error"
                  message:
                    type: string
                    example: "Health check failure due to unexpected error."
                  timestamp:
                    type: string
                    format: date-time
                    example: "2024-11-09T12:02:00Z"
