openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9

servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing

paths:
  /health:
    get:
      summary: Health check endpoint
      description: This endpoint checks the health of the service instance by performing various checks, such as infrastructure connections, host status, and application-specific logic.
      responses:
        "200":
          description: The service is healthy and capable of handling requests.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "healthy"
                  message:
                    type: string
                    example: "The service is healthy and capable of handling requests."
                  timestamp:
                    type: string
                    format: date-time
                    example: "2024-11-09T12:00:00Z"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
