# Generated by Django 5.1.4 on 2025-02-08 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("matching", "MATCHING"),
                            ("playing", "PLAYING"),
                            ("end", "END"),
                            ("canceled", "CANCELED"),
                        ],
                        default="matching",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "tournaments",
            },
        ),
        migrations.CreateModel(
            name="Round",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("round_number", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "IN_PROGRESS"),
                            ("completed", "COMPLETED"),
                            ("canceled", "CANCELED"),
                        ],
                        default="in_progress",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tournament",
                    models.ForeignKey(
                        db_column="tournament_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="round",
                        to="tournaments.tournament",
                    ),
                ),
            ],
            options={
                "db_table": "rounds",
            },
        ),
        migrations.CreateModel(
            name="Participation",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("participation_name", models.CharField(max_length=255)),
                (
                    "ranking",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "player",
                    models.ForeignKey(
                        db_column="player_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournament_participations",
                        to="accounts.player",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        db_column="tournament_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournament_participations",
                        to="tournaments.tournament",
                    ),
                ),
            ],
            options={
                "db_table": "tournament_participations",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tournament_id", "player_id"),
                        name="unique_tournament_participation",
                    )
                ],
            },
        ),
    ]
