const AuthCode = {
  LOGIN_ERROR: "LOGIN_ERROR",
  EMAIL_VALID: "EMAIL_VALID",
  EMAIL_INVALID_FORMAT: "EMAIL_INVALID_FORMAT",
  PASSWORD_VALID: "PASSWORD_VALID",
  PASSWORD_INVALID_LENGTH: "PASSWORD_INVALID_LENGTH",
  PASSWORD_INVALID_CHAR: "PASSWORD_INVALID_CHAR",
  PASSWORD_INVALID_ALL_NUMS: "PASSWORD_INVALID_ALL_NUMS",
};

export const MessageEnums = Object.freeze({
  AuthCode,
});
