# Generated by Django 5.1.4 on 2025-03-08 04:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0002_rename_is_two_factor_auth_twofactorauth_is_done_2fa"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="twofactorauth",
            name="qr_code_path",
        ),
    ]
