name: Backend Code Check

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  backend-code-check:
    # PR元が 'feature/backend/*' のブランチからの場合にトリガー
    if: startsWith(github.head_ref, 'feature/backend/')
    runs-on: ubuntu-latest  # GitHub Actionsで使用する環境

    steps:
      # ソースコードをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v4

      # Pythonのセットアップ
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'  # Pythonのバージョンを指定

      # 依存関係のインストール
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      # RuffによるLinterチェック
      - name: Run Ruff Linter
        run: make lint-be

      # Ruffによるフォーマットチェック
      - name: Run Ruff Formatter
        run: make format-be

      # Mypyによる型チェック
      - name: Run Mypy Type Checker
        run: make typecheck-be
