# Generated by Django 5.1.4 on 2024-12-29 09:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("oauth2", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fortytwotoken",
            old_name="user",
            new_name="oauth2",
        ),
    ]
