name: Backend Unit Test

on:
  pull_request:
    paths:
      - 'backend/pong/**'
      - '.github/workflows/backend_unit_test.yml'

jobs:
  backend-unit-test:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 5432:5432
          - 8000:8000
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # backendコンテナ内のテストがDBコンテナに依存しているため、2つのサービスを起動する
      - name: Set up Docker Compose
        run: |
          docker compose -f compose.yaml up -d backend db

      - name: Wait for db service to be ready
        run: |
          while ! docker compose -f compose.yaml exec -T db pg_isready -U user; do sleep 1; done

      - name: Run Backend Unit Test
        run: docker compose -f compose.yaml exec -T backend make unit-test

      # backendのユニットテストを実行
      - name: Tear down Docker Compose
        run: docker compose -f compose.yaml down
