name: Frontend Code Check

on:
  pull_request:
    paths:
      - 'frontend/pong/**'
      - '.github/workflows/frontend_code_check.yml'


jobs:
  frontend-code-check:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: 1.9.4
      - name: Run Biome
        run: biome ci .
        working-directory: frontend/pong
